import 'tailwindcss/tailwind.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
    <body>
        <section className="text-gray-600 body-font">
            <div className="container px-5 py-24 mx-auto">
            {children}
            </div>
        </section>
    </body>
  </html>
)
}
